// --- Room Definition ---
w.r_woods = #{
	name: "Woods",
	description: "TODO",
	initial_message: "You feel the cold wind blowing at your face. You open your eyes and see nothing but darkness. While slowly trying to standup, your eyes adjust and you realize that you were lying on the floor in the woods near your house. How did you get there is something that you cannot remember. The last thing that you recall was drinking foreign beer with your best friend Marko. `Man, that guy is a legend` you said out loud.",
	visited_count: 0
};